version: '3'

services:
  elastic:
    image: blacktop/elasticsearch:6
    environment:
      - DOMAIN_NAME=elastic.${BASEHOST:-dev}

  elastic-hq:
    image: elastichq/elasticsearch-hq
    environment:
      - DOMAIN_NAME=hq.${BASEHOST:-elastic.dev}
